### ISSUE TITLE
Does not work with tiling

### ISSUE THREAD

**Issue by Radivarig** [carlmartus/aseprite_normalmap#1]
Edges are sharp around the border even when the color is the same when tiled.

**Comment by carlmartus** [comment]
Hi @Radivarig, I've uploaded a PR that should fix your problem. Please have a look at it and let me know if it works on your side.

- PR: #2 
- [Direct link to script](https://raw.githubusercontent.com/carlmartus/aseprite_normalmap/1-does-not-work-with-tiling/Normal%20map%20from%20height%20map.lua)

**Comment by Radivarig** [comment]
@carlmartus yep it works, thanks!
